# Generated by Django 4.1.7 on 2023-03-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("thumb", models.ImageField(upload_to="product/thumb")),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField()),
                ("updated", models.DateField(auto_now=True)),
                ("timestamp", models.DateField(auto_now_add=True)),
                ("slug", models.SlugField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="StockModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("quantity", models.IntegerField(default=1)),
                ("updated", models.DateField(auto_now=True)),
                ("timestamp", models.DateField(auto_now_add=True)),
                ("slug", models.SlugField(default=None)),
                (
                    "prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productmodel",
                        verbose_name="prod",
                    ),
                ),
            ],
        ),
    ]
