# Generated by Django 4.1.7 on 2023-03-20 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "po",
                    models.FileField(blank=True, null=True, upload_to="sales/upload/"),
                ),
                ("cgst", models.CharField(blank=True, max_length=50, null=True)),
                ("sgst", models.CharField(blank=True, max_length=50, null=True)),
                ("igst", models.CharField(blank=True, max_length=50, null=True)),
                ("cess", models.CharField(blank=True, max_length=50, null=True)),
                ("tcs", models.CharField(blank=True, max_length=50, null=True)),
                ("updated", models.DateField(auto_now=True)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gstin", models.CharField(max_length=15)),
                ("destination", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "po",
                    models.FileField(blank=True, null=True, upload_to="sales/upload/"),
                ),
                ("cgst", models.CharField(blank=True, max_length=50, null=True)),
                ("sgst", models.CharField(blank=True, max_length=50, null=True)),
                ("igst", models.CharField(blank=True, max_length=50, null=True)),
                ("cess", models.CharField(blank=True, max_length=50, null=True)),
                ("tcs", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suplier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("perprice", models.IntegerField(default=1)),
                ("totalprice", models.IntegerField(default=1)),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salebillno",
                        to="transactions.salebill",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saleitem",
                        to="product.stockmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleBillDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eway", models.CharField(blank=True, max_length=50, null=True)),
                ("veh", models.CharField(blank=True, max_length=50, null=True)),
                ("po", models.CharField(blank=True, max_length=50, null=True)),
                ("cgst", models.CharField(blank=True, max_length=50, null=True)),
                ("sgst", models.CharField(blank=True, max_length=50, null=True)),
                ("igst", models.CharField(blank=True, max_length=50, null=True)),
                ("cess", models.CharField(blank=True, max_length=50, null=True)),
                ("tcs", models.CharField(blank=True, max_length=50, null=True)),
                ("total", models.IntegerField(default=0)),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saledetailsbillno",
                        to="transactions.salebill",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("perprice", models.IntegerField(default=1)),
                ("totalprice", models.IntegerField(default=1)),
                (
                    "billno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchasebillno",
                        to="transactions.purchasebill",
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchaseitem",
                        to="product.stockmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="purchasebill",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchasesupplier",
                to="transactions.supplier",
            ),
        ),
    ]
